# Generated by Django 6.0.6 on 2026-07-04 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='جواب')),
                ('category', models.CharField(choices=[('general', 'عمومی'), ('internet', 'اینترنت'), ('dormitory', 'خوابگاه'), ('rights', 'حقوق'), ('facilities', 'تأسیسات'), ('other', 'سایر')], default='general', max_length=20, verbose_name='دسته\u200cبندی')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='لایک')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='دیسلایک')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(verbose_name='لایک')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='faq.faq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رای FAQ',
                'unique_together': {('faq', 'user')},
            },
        ),
    ]
