# Generated by Django 6.0.6 on 2026-07-04 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(max_length=20, unique=True, verbose_name='کد پرسنلی')),
                ('shift_start', models.TimeField(verbose_name='شروع شیفت')),
                ('shift_end', models.TimeField(verbose_name='پایان شیفت')),
                ('status', models.CharField(choices=[('available', 'آماده به کار'), ('busy', 'مشغول'), ('off_shift', 'پایان شیفت')], default='off_shift', max_length=20, verbose_name='وضعیت حضور')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='reports.specialty', verbose_name='تخصص')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تکنسین',
                'verbose_name_plural': 'تکنسین\u200cها',
                'ordering': ['user__last_name'],
            },
        ),
    ]
