# Generated by Django 4.2.30 on 2026-07-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_id_verified',
            field=models.BooleanField(default=False, verbose_name='هویت تایید شده'),
        ),
    ]
