# Generated by Django 6.0.6 on 2026-07-04 20:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دانشکده')),
            ],
            options={
                'verbose_name': 'دانشکده',
                'verbose_name_plural': 'دانشکده\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خرابی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای خرابی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200, verbose_name='نام قطعه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'درخواست قطعه',
                'verbose_name_plural': 'درخواست\u200cهای قطعه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'ثبت گزارش'), ('assigned', 'ارجاع به تکنسین'), ('heading', 'در حال رفتن به محل'), ('arrived', 'حضور در محل'), ('started', 'شروع تعمیر'), ('suspended', 'تعلیق'), ('resumed', 'ازسرگیری'), ('completed', 'اتمام تعمیر'), ('rated', 'امتیازدهی'), ('closed', 'بسته شدن'), ('cancelled', 'لغو'), ('reassigned', 'ارجاع مجدد'), ('priority_changed', 'تغییر اولویت')], max_length=30, verbose_name='عملیات')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'لاگ تعمیر',
                'verbose_name_plural': 'لاگ\u200cهای تعمیر',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خرابی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='reports/audio/', verbose_name='فایل صوتی')),
                ('priority', models.CharField(choices=[('normal', 'عادی'), ('important', 'مهم'), ('urgent', 'اضطراری')], default='normal', max_length=20, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('pending', 'در صف انتظار'), ('assigned', 'ارجاع شده'), ('in_progress', 'در حال تعمیر'), ('suspended', 'معلق'), ('resolved', 'حل شده'), ('closed', 'بسته شده'), ('cancelled', 'لغو شده'), ('archived', 'بایگانی')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('eta_hours', models.FloatField(blank=True, null=True, verbose_name='زمان تخمینی (ساعت)')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز رضایت')),
                ('objection_text', models.TextField(blank=True, verbose_name='متن اعتراض')),
                ('suspension_reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل تعلیق')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='دلیل لغو')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارجاع')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بسته شدن')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='reports/images/', verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو')], default='image', max_length=10, verbose_name='نوع فایل')),
                ('is_after', models.BooleanField(default=False, verbose_name='عکس بعد از تعمیر')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رسانه گزارش',
                'verbose_name_plural': 'رسانه\u200cهای گزارش',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تخصص')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='reports/messages/', verbose_name='پیوست')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام ساختمان')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='reports.faculty')),
            ],
            options={
                'verbose_name': 'ساختمان',
                'verbose_name_plural': 'ساختمان\u200cها',
                'ordering': ['faculty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='طبقه')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='اتاق')),
                ('location_type', models.CharField(choices=[('faculty', 'دانشکده'), ('dormitory', 'خوابگاه'), ('cafeteria', 'سلف'), ('library', 'کتابخانه'), ('gym', 'ورزشگاه'), ('other', 'سایر')], default='faculty', max_length=20, verbose_name='نوع مکان')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='reports.building')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان\u200cها',
                'ordering': ['building', 'floor', 'room'],
            },
        ),
    ]
