# Generated by Django 6.0.6 on 2026-07-04 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('technicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_requests', to='technicians.technician'),
        ),
        migrations.AddField(
            model_name='repairlog',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_logs', to='technicians.technician'),
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.faultcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.location', verbose_name='مکان'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='report',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='technicians.technician', verbose_name='تکنسین'),
        ),
        migrations.AddField(
            model_name='repairlog',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reports.report'),
        ),
        migrations.AddField(
            model_name='partrequest',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_requests', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportmedia',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='reports.report'),
        ),
        migrations.AddField(
            model_name='faultcategory',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='reports.specialty'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reports.report'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
