# Generated by Django 6.0.6 on 2026-07-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('status_change', 'تغییر وضعیت'), ('technician_assigned', 'اتصال تکنسین'), ('new_message', 'پیام جدید'), ('resolved', 'حل شدن'), ('part_approved', 'تایید قطعه'), ('part_rejected', 'رد قطعه'), ('rating_reminder', 'یادآوری امتیاز')], max_length=30, verbose_name='نوع')),
                ('message', models.TextField(verbose_name='متن اعلان')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
